Feature/search contributors
ACM-VIT/iOS-Feature-Park pull request #15
Opened 2020-10-11 14:15 UTC by NiklasOemler

### Description
Implemented a UISeachController to contributorTableViewController and myself to the contributor datasource.

Fixes #3 

![Bildschirmfoto 2020-10-11 um 16 10 56](https://user-images.githubusercontent.com/55978783/95680823-83fc6900-0bdc-11eb-9794-d779f6b65917.png)
![Bildschirmfoto 2020-10-11 um 16 11 11](https://user-images.githubusercontent.com/55978783/95680825-88288680-0bdc-11eb-8393-51737dab2756.png)

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Search a contributor in the Datasource.contributors. It checks if the datasource contains the lowercased search string and overrides the value of the filteredContributors property. If no then it takes the initial value of datasource.contributors.  

### Checklist:

- [x ] My PR follows the style guidelines of this project
- [ x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x ] My changes generate no new warnings

2020-10-12 04:11 UTC, swamitagupta approved these changes
@NiklasOemler good job!

2020-10-12 04:20 UTC, aaryankotharii commented
Hi @NiklasOemler, thank you for your interest in working on this issue!
I will be quickly pointing out some minor requisite changes in the code.

2020-10-12 04:28 UTC, aaryankotharii requested changes

2020-10-12 04:28 UTC, aaryankotharii commented on Hacktoberfest iOS/Controller/ContributorTableViewController.swift
> +    var filteredContributors : [ContributorModel]!
instead of force unwrapping `filteredContributors` as an array of `ContributorModel`, we can rather declare it as an empty array of the type `ContributorModel`.
```Swift
var filteredContributors : [ContributorModel] = []
var filteredContributors = [ContributorModel]()
```

any of the two ways can be used

2020-10-12 04:28 UTC, aaryankotharii commented on Hacktoberfest iOS/Controller/ContributorTableViewController.swift
> +    var isSeachBarEmpty : Bool {
great use of the computed property here!

2020-10-12 04:28 UTC, aaryankotharii commented on Hacktoberfest iOS/Controller/ContributorTableViewController.swift
> +            for contributor in Datasource.contributors {
I see that you are running a `for` loop and appending elements based on a condition here. This is the exact reason why Apple introduced the `Filter` method. we can use it to easily filter `Datasource.contributors`, this will reduce our code length and will make it easier for contributors to comprehend the code.
know more [here](https://developer.apple.com/documentation/swift/sequence/3018365-filter)

2020-10-12 04:28 UTC, aaryankotharii commented
also @NiklasOemler, please take a pull from upstream master to avoid merge conflicts.

2020-10-12 07:02 UTC, NiklasOemler commented on Hacktoberfest iOS/Controller/ContributorTableViewController.swift
> +    var filteredContributors : [ContributorModel]!
thanks for this improvement! Ive just started learning swift in my free time, at work I only need objective c and im still not 100% sure about optionals and unwrapping in swift, its confusing me :(

2020-10-12 07:10 UTC, NiklasOemler commented
> also @NiklasOemler, please take a pull from upstream master to avoid merge conflicts.

yep you're right, its also my first time contributing on a open source repo where I have to add an remote upstream. I'll merge the upstream master into my feature branch. But when do I need my origin/master on my forked repo then?

2020-10-12 08:05 UTC, NiklasOemler commented
@aaryankotharii I updated my feature branch. 
Thank your for your tips, really appreciated.

2020-10-13 03:37 UTC, aaryankotharii commented
LGTM! Thank you for your contribution @NiklasOemler and I'm glad you could learn something new.
Approved.

2020-10-13 03:38 UTC, aaryankotharii approved these changes

2020-10-13 03:38 UTC, merged